"""A communication frontend bound to one existing native Codex thread.

No credentials, HTTP signaling, microphone, recorder, or task executor live here.
The caller must retain the native process and exclusive scope/event-consumer lease.
Shapes are the experimental app-server protocol generated by Codex 0.159.2.
"""
import hashlib
import os
import threading
import time
import uuid

from .codex import CodexError


class LiveError(ValueError):
    """Public, deliberately non-secret error code."""


def _text(value, name):
    if not isinstance(value, str) or not value.strip():
        raise LiveError('live_invalid_' + name)
    return value


def _audio(value):
    # The schema says string, not PCM or base64. Do not guess its wire encoding.
    if not isinstance(value, dict) or set(value) - {
            'data', 'numChannels', 'sampleRate', 'samplesPerChannel', 'itemId'}:
        raise LiveError('live_invalid_audio')
    result = dict(value)
    _text(result.get('data'), 'audio_data')
    for key, maximum in (('numChannels', 65535), ('sampleRate', 4294967295)):
        number = result.get(key)
        if type(number) is not int or not 1 <= number <= maximum:
            raise LiveError('live_invalid_audio_' + key)
    samples = result.get('samplesPerChannel')
    if samples is not None and (type(samples) is not int or not 0 <= samples <= 4294967295):
        raise LiveError('live_invalid_audio_samplesPerChannel')
    if result.get('itemId') is not None:
        _text(result['itemId'], 'audio_itemId')
    return result


class CodexLiveTransport:
    """Adapter around an already loaded Codex, never around a new summary thread.

    Only one Live adapter is allowed per Codex process. Flat realtime events lack
    a session id, so attaching a replacement while an old stream lingers is unsafe.
    Do not concurrently call Codex.finish/event: the owner must multiplex events.
    """
    METHODS = frozenset(('start', 'appendText', 'appendAudio', 'appendSpeech', 'stop'))

    def __init__(self, agent, thread_id, lease_check, expected_auth_home=None):
        self.agent = agent
        self.thread_id = _text(thread_id, 'thread_id')
        # Communication account selection is an explicit deployment pin, not the
        # inference account pool. Inspect paths only, never auth.json contents.
        self.auth_home = os.path.realpath(_text(expected_auth_home, 'communication_auth_home'))
        if os.path.realpath(getattr(agent, 'auth_home', '') or '') != self.auth_home:
            raise LiveError('live_communication_account_mismatch')
        if not callable(lease_check):
            raise LiveError('live_lease_check_required')
        self.lease_check = lease_check
        self.lock = threading.RLock()
        if getattr(agent, 'thread_id', None) != self.thread_id:
            raise LiveError('live_native_thread_not_loaded')
        if getattr(agent, '_mesh_live_transport', None) is not None:
            raise LiveError('live_native_stream_already_bound')
        agent._mesh_live_transport = self

    def _guard(self):
        try:
            valid = self.lease_check() is True
        except Exception:
            valid = False
        if not valid:
            raise LiveError('live_lease_lost')
        if getattr(self.agent, 'thread_id', None) != self.thread_id:
            raise LiveError('live_native_thread_changed')
        if os.path.realpath(getattr(self.agent, 'auth_home', '') or '') != self.auth_home:
            raise LiveError('live_communication_account_changed')

    def validate(self, binding):
        self._guard()
        if binding['thread_id'] != self.thread_id:
            raise LiveError('live_native_thread_mismatch')
        account = self.agent.account()
        if not account.get('authenticated') or account.get('type') != 'chatgpt':
            # A subscription is not a project API key; never silently change routes.
            raise LiveError('live_chatgpt_subscription_required')

    def rpc(self, method, params, timeout=30):
        with self.lock:
            self._guard()
            if not method.startswith('thread/realtime/') or method.rsplit('/', 1)[-1] not in self.METHODS:
                raise LiveError('live_invalid_native_method')
            if params.get('threadId') != self.thread_id:
                raise LiveError('live_native_thread_mismatch')
            try:
                return self.agent.rpc(method, params, timeout=timeout)
            except CodexError as exc:
                if str(exc).startswith('codex_rpc_failed_'):
                    raise LiveError('live_rpc_rejected') from None
                raise LiveError('live_rpc_unknown') from None
            except (OSError, ValueError):
                raise LiveError('live_rpc_unknown') from None

    def _matches(self, event):
        return (isinstance(event, dict) and isinstance(event.get('method'), str)
                and event['method'].startswith('thread/realtime/')
                and isinstance(event.get('params'), dict)
                and event['params'].get('threadId') == self.thread_id)

    def poll(self, timeout=1):
        with self.lock:
            self._guard()
            # rpc may receive notifications before its response. Preserve all
            # unrelated native turn/tool/other-thread events in their original order.
            for index, event in enumerate(self.agent.deferred):
                if self._matches(event):
                    return self.agent.deferred.pop(index)
            deadline = time.monotonic() + max(0, timeout)
            while time.monotonic() < deadline:
                try:
                    event = self.agent.event(timeout=max(.001, deadline - time.monotonic()))
                except CodexError as exc:
                    if str(exc) == 'codex_timeout':
                        return None
                    raise LiveError('live_transport_unknown') from None
                if self._matches(event):
                    return event
                self.agent.deferred.append(event)
            return None


class LiveSession:
    """One fixed source/peer/scope/thread binding and an explicit permission gate.

    authorize(binding, action) and lease_check(binding) must return literal True.
    Callers provide trusted identity, never an ingress-supplied role or grant.
    Transcripts/audio are forwarded only to opt-in, separately authorized sinks;
    snapshots contain metadata, not the private conversation or audio payload.
    """
    TERMINAL = ('closed', 'detached')
    VOICES = frozenset(('alloy', 'arbor', 'ash', 'ballad', 'breeze', 'cedar', 'coral',
        'cove', 'echo', 'ember', 'juniper', 'maple', 'marin', 'sage', 'shimmer', 'sol',
        'spruce', 'vale', 'verse'))

    def __init__(self, transport, binding, authorize=None, lease_check=None,
                 on_event=None, on_audio=None, session_id=None):
        if not isinstance(binding, dict):
            raise LiveError('live_invalid_binding')
        required = ('thread_id', 'scope', 'principal', 'source', 'peer')
        self._binding = {key: _text(binding.get(key), key) for key in required}
        if binding.get('call_id') is not None:
            self._binding['call_id'] = _text(binding['call_id'], 'call_id')
        self.transport = transport
        self.authorize = authorize or (lambda binding, action: False)
        self.lease_check = lease_check or (lambda binding: False)
        self.on_event, self.on_audio = on_event, on_audio
        self.session_id = _text(session_id or str(uuid.uuid4()), 'session_id')
        self.state, self.output_modality = 'idle', None
        self.submissions, self.items = {}, {}
        self.evidence = {'request_accepted': False, 'native_started': False,
            'native_closed': False, 'transcript_events': 0, 'output_audio_chunks': 0,
            'output_audio_encoded_chars': 0, 'sink_delivery_unknown': 0, 'signaling_events': 0}
        self._stop_submitted = False
        self._start_submitted = False
        self.last_error = None
        self.lock = threading.RLock()

    @property
    def binding(self):
        return dict(self._binding)

    def snapshot(self):
        return {'session_id': self.session_id, 'binding': self.binding, 'state': self.state,
                'output_modality': self.output_modality, 'evidence': dict(self.evidence),
                'last_error': self.last_error, 'submission_count': len(self.submissions),
                'item_count': len(self.items)}

    def _lease(self):
        try:
            valid = self.lease_check(self.binding) is True
        except Exception:
            valid = False
        if not valid:
            self.state = 'detached'
            raise LiveError('live_lease_lost')

    def _allowed(self, action):
        try:
            return self.authorize(self.binding, action) is True
        except Exception:
            return False

    def _guard(self, action):
        self._lease()
        if not self._allowed(action):
            raise LiveError('live_permission_denied_' + action)

    def _failure(self, error):
        self.last_error = str(error) if isinstance(error, LiveError) else 'live_rpc_unknown'
        self.state = ('detached' if self.last_error == 'live_lease_lost' else
                      'error' if self.last_error in ('live_rpc_rejected', 'live_native_thread_changed') else 'unknown')
        return LiveError(self.last_error)

    def start(self, output_modality='text', version=None, model=None, voice=None,
              transport=None, timeout=30):
        with self.lock:
            if self._start_submitted or self.state != 'idle':
                raise LiveError('live_start_already_submitted')
            self._guard('connect')
            if output_modality not in ('text', 'audio'):
                raise LiveError('live_invalid_output_modality')
            if output_modality == 'audio':
                self._guard('receive_audio')
            params = {'threadId': self._binding['thread_id'], 'outputModality': output_modality,
                      'realtimeSessionId': self.session_id}
            if version is not None:
                if version not in ('v1', 'v2', 'v3'):
                    raise LiveError('live_invalid_version')
                params['version'] = version
            if model is not None:
                params['model'] = _text(model, 'model')
            if voice is not None:
                if voice not in self.VOICES:
                    raise LiveError('live_invalid_voice')
                params['voice'] = voice
            if transport is not None:
                if not isinstance(transport, dict):
                    raise LiveError('live_invalid_transport')
                shape = {'websocket': {'type'}, 'webrtc': {'type', 'sdp'},
                         'existingCall': {'type', 'callId'}}.get(transport.get('type'))
                if shape is None or set(transport) != shape:
                    raise LiveError('live_invalid_transport')
                if transport['type'] == 'webrtc':
                    _text(transport['sdp'], 'sdp')
                if transport['type'] == 'existingCall':
                    self._guard('attach_call')
                    if transport['callId'] != self._binding.get('call_id'):
                        raise LiveError('live_call_identity_mismatch')
                params['transport'] = dict(transport)
            self.transport.validate(self.binding)
            self.state, self.output_modality = 'starting', output_modality
            self._start_submitted = True
            try:
                self.transport.rpc('thread/realtime/start', params, timeout=timeout)
            except Exception as exc:
                raise self._failure(exc) from None
            self.evidence['request_accepted'] = True
            return self.snapshot()

    def _submit(self, method, value, submission_id, action):
        with self.lock:
            self._guard(action)
            submission_id = _text(submission_id, 'submission_id')
            digest = hashlib.sha256((method + '\0' + value).encode('utf8')).hexdigest()
            previous = self.submissions.get(submission_id)
            if previous:
                if previous['digest'] != digest:
                    raise LiveError('live_submission_id_conflict')
                return dict(previous)
            if self.state not in ('started', 'exchanging') or self._stop_submitted:
                raise LiveError('live_not_started')
            record = {'id': submission_id, 'digest': digest, 'method': method, 'status': 'submitting'}
            self.submissions[submission_id] = record
            try:
                self.transport.rpc('thread/realtime/' + method,
                                   {'threadId': self._binding['thread_id'], 'text': value})
            except Exception as exc:
                record['status'] = 'rejected' if isinstance(exc, LiveError) and str(exc) == 'live_rpc_rejected' else 'unknown'
                raise self._failure(exc) from None
            record['status'] = 'accepted'
            # appendText has no client correlation id on the native wire. Never
            # invent an association between this ack and a later flat transcript.
            return dict(record)

    def append_text(self, text, message_id):
        return self._submit('appendText', _text(text, 'text'), message_id, 'send_text')

    def append_speech(self, text, handoff_id):
        # Reserved for authorized results from this same bound continuous Leader.
        return self._submit('appendSpeech', _text(text, 'speech'), handoff_id, 'speak_result')

    def append_audio(self, audio):
        with self.lock:
            self._guard('send_audio')
            if self.state not in ('started', 'exchanging') or self._stop_submitted:
                raise LiveError('live_not_started')
            value = _audio(audio)
            try:
                self.transport.rpc('thread/realtime/appendAudio',
                                   {'threadId': self._binding['thread_id'], 'audio': value})
            except Exception as exc:
                raise self._failure(exc) from None
            return {'status': 'accepted', 'encoded_chars': len(value['data'])}

    def _deliver(self, event, permission):
        if self.on_event and self._allowed(permission):
            try:
                self.on_event(dict(event))
            except Exception:
                self.evidence['sink_delivery_unknown'] += 1
                raise LiveError('live_sink_delivery_unknown') from None

    def handle(self, event):
        with self.lock:
            if self.state in self.TERMINAL:
                return False
            self._lease()
            if (not isinstance(event, dict) or not isinstance(event.get('params'), dict)
                    or event['params'].get('threadId') != self._binding['thread_id']):
                return False
            method, params = event.get('method'), event['params']
            if not self._start_submitted:
                return False
            if method == 'thread/realtime/started':
                if (params.get('version') not in ('v1', 'v2', 'v3') or
                        params.get('realtimeSessionId') not in (None, self.session_id)):
                    self.last_error, self.state = 'live_session_identity_mismatch', 'error'
                    return True
                if not self._start_submitted:
                    return False
                self.evidence['native_started'] = True
                if not self._stop_submitted and self.state not in ('error',):
                    self.state = 'started'
                return True
            if method == 'thread/realtime/error':
                # Raw server messages can contain credentials or private context.
                self.last_error, self.state = 'live_native_error', 'error'
                return True
            if method == 'thread/realtime/closed':
                self.evidence['native_closed'], self.state = True, 'closed'
                return True
            if method == 'thread/realtime/sdp':
                if not isinstance(params.get('sdp'), str) or not params['sdp'].strip():
                    return False
                self.evidence['signaling_events'] += 1
                self._deliver({'type': 'sdp', 'sdp': params['sdp'],
                               'session_id': self.session_id}, 'receive_signaling')
                return True
            if self.state not in ('started', 'exchanging') or self._stop_submitted:
                return False
            if method in ('thread/realtime/transcript/delta', 'thread/realtime/transcript/done'):
                field = 'delta' if method.endswith('/delta') else 'text'
                if not isinstance(params.get(field), str) or not isinstance(params.get('role'), str):
                    return False
                self.evidence['transcript_events'] += 1
                self.state = 'exchanging'
                self._deliver({'type': 'transcript', 'role': params['role'], field: params[field],
                               'session_id': self.session_id}, 'read_transcript')
                return True
            if method == 'thread/realtime/outputAudio/delta':
                value = _audio(params.get('audio'))
                self.evidence['output_audio_chunks'] += 1
                self.evidence['output_audio_encoded_chars'] += len(value['data'])
                self.state = 'exchanging'
                if self.output_modality == 'audio' and self.on_audio and self._allowed('receive_audio'):
                    try:
                        self.on_audio(dict(value), self.binding)
                    except Exception:
                        self.evidence['sink_delivery_unknown'] += 1
                        raise LiveError('live_sink_delivery_unknown') from None
                return True
            if method in ('thread/realtime/item/started', 'thread/realtime/item/completed'):
                item = params.get('item')
                if (not isinstance(item, dict) or not isinstance(item.get('id'), str)
                        or item.get('realtimeSessionId') != self.session_id):
                    return False
                old = self.items.get(item['id'], {'id': item['id'], 'delta_chars': 0})
                status = 'completed' if method.endswith('/completed') else 'started'
                # A delayed start must not downgrade an already committed item.
                if old.get('status') != 'completed':
                    old['status'] = status
                old['type'] = item.get('type')
                self.items[item['id']] = old
                if item.get('type') == 'transcriptSegment' and isinstance(item.get('text'), str):
                    digest = hashlib.sha256(item['text'].encode('utf8')).hexdigest()
                    if status == 'completed' and old.get('text_digest') != digest:
                        old['text_digest'] = digest
                        self.evidence['transcript_events'] += 1
                        self.state = 'exchanging'
                        self._deliver({'type': 'transcript', 'item_id': item['id'],
                            'role': item.get('role'), 'text': item['text'],
                            'session_id': self.session_id}, 'read_transcript')
                return True
            if method == 'thread/realtime/item/transcript/delta':
                if not isinstance(params.get('itemId'), str) or not isinstance(params.get('delta'), str):
                    return False
                item = self.items.get(params['itemId'])
                # Do not accept an unbound id from another/old session's timeline.
                if item is None or item.get('status') == 'completed':
                    return False
                item['delta_chars'] += len(params['delta'])
                self.evidence['transcript_events'] += 1
                self.state = 'exchanging'
                self._deliver({'type': 'transcript_delta', 'item_id': params['itemId'],
                    'delta': params['delta'], 'session_id': self.session_id}, 'read_transcript')
                return True
            # Opaque itemAdded/delegation payloads are not new task authority.
            return False

    def step(self, timeout=1):
        if self.state in self.TERMINAL:
            return self.snapshot()
        self._lease()
        try:
            event = self.transport.poll(timeout=timeout)
        except Exception as exc:
            raise self._failure(exc) from None
        if event is not None:
            self.handle(event)
        return self.snapshot()

    def wait_started(self, timeout=30):
        deadline = time.monotonic() + timeout
        while time.monotonic() < deadline and self.state in ('starting', 'unknown'):
            self.step(min(1, max(.001, deadline - time.monotonic())))
        if self.state in ('error', 'closed', 'detached'):
            raise LiveError('live_start_failed')
        if not self.evidence['native_started']:
            # An observation timeout does not end/restart the still-live attempt.
            raise LiveError('live_started_not_observed')
        return self.snapshot()

    def stop(self, timeout=30):
        with self.lock:
            if self.state in self.TERMINAL:
                return self.snapshot()
            try:
                self._lease()
            except LiveError:
                # Do not stop a thread now owned by a replacement Leader.
                return self.snapshot()
            if not self._start_submitted:
                self.state = 'closed'
                return self.snapshot()
            if self._stop_submitted:
                return self.snapshot()
            self._stop_submitted, self.state = True, 'stopping'
            try:
                self.transport.rpc('thread/realtime/stop',
                                   {'threadId': self._binding['thread_id']}, timeout=timeout)
            except Exception as exc:
                raise self._failure(exc) from None
            # Stop ack is not a closed event, nor proof that audio was played.
            return self.snapshot()
